/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CvRouteImport } from './routes/cv'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements.index'
import { Route as AnnouncementsAnnouncementIdRouteImport } from './routes/announcements.$announcementId'
import { Route as AnnouncementsNewRouteImport } from './routes/announcements.new'
import { Route as BugsIndexRouteImport } from './routes/bugs.index'
import { Route as BugsBugIdRouteImport } from './routes/bugs.$bugId'
import { Route as DashboardBackupRouteImport } from './routes/dashboard.backup'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeopleUserIdRouteImport } from './routes/people.$userId'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsAnnouncementIdRoute =
  AnnouncementsAnnouncementIdRouteImport.update({
    id: '/announcements/$announcementId',
    path: '/announcements/$announcementId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnnouncementsNewRoute = AnnouncementsNewRouteImport.update({
  id: '/announcements/new',
  path: '/announcements/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BugsIndexRoute = BugsIndexRouteImport.update({
  id: '/bugs/',
  path: '/bugs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BugsBugIdRoute = BugsBugIdRouteImport.update({
  id: '/bugs/$bugId',
  path: '/bugs/$bugId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBackupRoute = DashboardBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => DashboardRoute,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleUserIdRoute = PeopleUserIdRouteImport.update({
  id: '/people/$userId',
  path: '/people/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cv': typeof CvRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/debug': typeof DebugRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/announcements/$announcementId': typeof AnnouncementsAnnouncementIdRoute
  '/announcements/new': typeof AnnouncementsNewRoute
  '/bugs/$bugId': typeof BugsBugIdRoute
  '/dashboard/backup': typeof DashboardBackupRoute
  '/people/$userId': typeof PeopleUserIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/bugs/': typeof BugsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cv': typeof CvRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/debug': typeof DebugRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/announcements/$announcementId': typeof AnnouncementsAnnouncementIdRoute
  '/announcements/new': typeof AnnouncementsNewRoute
  '/bugs/$bugId': typeof BugsBugIdRoute
  '/dashboard/backup': typeof DashboardBackupRoute
  '/people/$userId': typeof PeopleUserIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/bugs': typeof BugsIndexRoute
  '/people': typeof PeopleIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cv': typeof CvRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/debug': typeof DebugRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/announcements/$announcementId': typeof AnnouncementsAnnouncementIdRoute
  '/announcements/new': typeof AnnouncementsNewRoute
  '/bugs/$bugId': typeof BugsBugIdRoute
  '/dashboard/backup': typeof DashboardBackupRoute
  '/people/$userId': typeof PeopleUserIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/bugs/': typeof BugsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cv'
    | '/dashboard'
    | '/debug'
    | '/messages'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/announcements/$announcementId'
    | '/announcements/new'
    | '/bugs/$bugId'
    | '/dashboard/backup'
    | '/people/$userId'
    | '/projects/$projectId'
    | '/announcements/'
    | '/bugs/'
    | '/people/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cv'
    | '/dashboard'
    | '/debug'
    | '/messages'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/announcements/$announcementId'
    | '/announcements/new'
    | '/bugs/$bugId'
    | '/dashboard/backup'
    | '/people/$userId'
    | '/projects/$projectId'
    | '/announcements'
    | '/bugs'
    | '/people'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cv'
    | '/dashboard'
    | '/debug'
    | '/messages'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/announcements/$announcementId'
    | '/announcements/new'
    | '/bugs/$bugId'
    | '/dashboard/backup'
    | '/people/$userId'
    | '/projects/$projectId'
    | '/announcements/'
    | '/bugs/'
    | '/people/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CvRoute: typeof CvRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DebugRoute: typeof DebugRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  AnnouncementsAnnouncementIdRoute: typeof AnnouncementsAnnouncementIdRoute
  AnnouncementsNewRoute: typeof AnnouncementsNewRoute
  BugsBugIdRoute: typeof BugsBugIdRoute
  PeopleUserIdRoute: typeof PeopleUserIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
  BugsIndexRoute: typeof BugsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$announcementId': {
      id: '/announcements/$announcementId'
      path: '/announcements/$announcementId'
      fullPath: '/announcements/$announcementId'
      preLoaderRoute: typeof AnnouncementsAnnouncementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/new': {
      id: '/announcements/new'
      path: '/announcements/new'
      fullPath: '/announcements/new'
      preLoaderRoute: typeof AnnouncementsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugs/': {
      id: '/bugs/'
      path: '/bugs'
      fullPath: '/bugs/'
      preLoaderRoute: typeof BugsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugs/$bugId': {
      id: '/bugs/$bugId'
      path: '/bugs/$bugId'
      fullPath: '/bugs/$bugId'
      preLoaderRoute: typeof BugsBugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/backup': {
      id: '/dashboard/backup'
      path: '/backup'
      fullPath: '/dashboard/backup'
      preLoaderRoute: typeof DashboardBackupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$userId': {
      id: '/people/$userId'
      path: '/people/$userId'
      fullPath: '/people/$userId'
      preLoaderRoute: typeof PeopleUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBackupRoute: typeof DashboardBackupRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBackupRoute: DashboardBackupRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CvRoute: CvRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DebugRoute: DebugRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  AnnouncementsAnnouncementIdRoute: AnnouncementsAnnouncementIdRoute,
  AnnouncementsNewRoute: AnnouncementsNewRoute,
  BugsBugIdRoute: BugsBugIdRoute,
  PeopleUserIdRoute: PeopleUserIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
  BugsIndexRoute: BugsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
